// Rewrite the instructions in your own words

// Write the objectives and the tests

// Write the pseudocode
/*  

1- We need to prompt the user to enter his email.
2- we need first to check if the email contain the name , @ , second level domain , top level domain.
3- to do that we need to check the existence of @ and (.)
4- if the @ symbol was there more than once we print invalid.
5- we check if there is any special character and if yes we print invalid.
6- we need to check the last (.) , if it come after @ , we can know if second level domain  and top level domain exists.
7- if @ come in the first of the email print invalid because that means no existence to name.
8- if (.) come immediately after @ then print invalid because that means no existence to second level domain.
9- if everything was checked okay then print valid.

*/


// paste your JS generated by blockly below here

var email, after, after1, after2, after3, after5;


email = window.prompt('Write your Email');
after = email.indexOf('@') + 1;
after1 = email.lastIndexOf('.') + 1;
after2 = email.indexOf(' ') + 1;
after3 = [email.indexOf('?') + 1,email.indexOf('/') + 1,email.indexOf('&') + 1,email.indexOf('%') + 1,email.indexOf('$') + 1,email.indexOf('£') + 1,email.indexOf('!') + 1,email.indexOf('=') + 1].join('');
after5 = email.lastIndexOf('@') + 1;
if (after == 0) {
  window.alert('invalid');
} else if (after1 == 0) {
  window.alert('invalid');
} else if (after1 < after) {
  window.alert('invalid');
} else if (after2 > 0) {
  window.alert('invalid');
} else if (after3 > 0) {
  window.alert('invalid');
} else if (after1 == after + 1) {
  window.alert('invalid');
} else if (after1 == email.length) {
  window.alert('invalid');
} else if (after == 1) {
  window.alert('invalid');
} else if (after5 > after) {
  window.alert('invalid');
} else if (after1 > after) {
  window.alert('valid');
}