// Rewrite the instructions in your own words 

// Write the objectives and the tests

// Write the pseudocode

/* 

1- prompt for a sentence
2- we need to take the first letter from each word and print them on a sting in upper case.

*/  


// paste your JS generated by blockly below here

var result, text, item;

function textToTitleCase(str) {
  return str.replace(/\S+/g,
      function(txt) {return txt[0].toUpperCase() + txt.substring(1).toLowerCase();});
}


result = '';
text = window.prompt('Write something');
text = textToTitleCase(text);
text = text.split(' ');
for (var item_index in text) {
  item = text[item_index];
  result += String(item.charAt(0));
}
window.alert(result);